### ISSUE TITLE
version does not increment as expected

### ISSUE THREAD

**Issue by jumanjiman** [greenpau/versioned#1]
Hi Paul,

nice utility and example usage for makefile!

## expected

- when minor version increments, patch should reset to zero
  - example: 1.0.1
  - expect after minor bump: 1.1.0
- when major version increments, both minor and patch should reset to zero
  - example: 1.1.1
  - expect after major bump: 2.0.0

## actual

```
/tmp/blah
❯ versioned -init

/tmp/blah
❯ cat VERSION
1.0.0

/tmp/blah
❯ versioned -patch
increased patch version by 1, current version: 1.0.1
updated version: 1.0.1, previous version: 1.0.0

/tmp/blah
❯ versioned -minor
increased minor version by 1, current version: 1.1.1
updated version: 1.1.1, previous version: 1.0.1

/tmp/blah
❯ versioned -major
increased major version by 1, current version: 2.1.1
updated version: 2.1.1, previous version: 1.1.1
```

**Comment by greenpau** [comment]
> when minor version increments, patch should reset to zero 

@jumanjiman , thank you very much my friend! :-) I didn't think about the counter restarts. I was mostly doing `-patch` :-) Will provide a fix!

**Comment by greenpau** [comment]
@jumanjiman , the tests are as follows:

https://github.com/greenpau/versioned/blob/780e294abfe59f26c9cfacca08cf42d0aa8567f1/versioned_test.go#L90-L116

**Comment by jumanjiman** [comment]
TYVM!

very useful 🙌
